# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20160215_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='docs:tags_autocomplete', blank=True, help_text='Entrez une liste de mots-clés séparés par des virgules', to='docs.DocumentTags', verbose_name='Mots-clés'),
        ),
    ]
