# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 14:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(verbose_name='Saison')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('name_m', models.CharField(max_length=100, verbose_name='Nom masculin')),
                ('name_f', models.CharField(max_length=100, verbose_name='Nom féminin')),
            ],
            options={
                'verbose_name': 'Fonction',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('\\d{6}', message="Le numéro d'adhérent comporte 6 chiffres")], verbose_name='Numéro')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Masculin'), (2, 'Féminin')], null=True, verbose_name='Genre')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super-utilisateur')),
            ],
            options={
                'verbose_name': 'Personne',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Tarif')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('\\d{10}', message='Le numéro de structure comporte 10 chiffres')], verbose_name='Numéro')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='members.Structure')),
            ],
            options={
                'verbose_name': 'Structure',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='adhesion',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Function', verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Person'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Rate', verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherents', to='members.Structure', verbose_name='Structure'),
        ),
    ]
