# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160217_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='committed',
            field=models.BooleanField(default=False, verbose_name='Engagé associatif'),
        ),
    ]
