# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rate_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tarif'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_after_tax_ex',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tarif après défiscalisation'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Nom'),
        ),
    ]
