# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160220_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='committed',
        ),
        migrations.AddField(
            model_name='rate',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Enfants'), (2, 'Cadres'), (3, 'Amis'), (4, 'Stagiaires'), (5, 'Services Vacances'), (6, 'Découverte')], null=True, verbose_name='Catégorie'),
        ),
    ]
