# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20160220_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='function',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='function',
            unique_together=set([('code', 'season')]),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('name', 'season')]),
        ),
    ]
