# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20160226_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Participants'), (2, 'Cadres bénévoles/CEE'), (3, 'Salariés'), (4, 'Amis')], null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='adhesion',
            name='sector',
            field=models.IntegerField(blank=True, choices=[(1, 'Groupes locaux'), (2, 'Formation'), (3, 'Services vacances'), (4, 'Activités ouvertes'), (5, 'Structures support')], null=True, verbose_name='Secteur'),
        ),
    ]
