# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20160226_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cercle'), (2, 'Clan Ainé'), (3, 'Comité directeur'), (4, 'Départementale fonctionnel'), (5, 'Pôle'), (6, 'Région'), (7, 'Ronde'), (8, 'Siège'), (9, 'Sommet'), (10, "Structure locale d'activité"), (11, 'Structure locale rattachée'), (12, 'Unité Défi'), (13, 'Unité Eclé'), (14, 'Unité Nomade')], default=0, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
