# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_structure_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adhesion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='sector',
        ),
        migrations.AddField(
            model_name='function',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Participants'), (2, 'Cadres bénévoles/CEE'), (3, 'Salariés'), (4, 'Amis')], null=True, verbose_name='Categorie'),
        ),
        migrations.AddField(
            model_name='function',
            name='sector',
            field=models.IntegerField(blank=True, choices=[(1, 'Groupes locaux'), (2, 'Formation'), (3, 'Services vacances'), (4, 'Activités ouvertes'), (5, 'Structures support')], null=True, verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.IntegerField(choices=[(1, 'Cercle'), (2, 'Clan Ainé'), (3, 'Comité directeur'), (4, 'Département'), (5, 'Pôle'), (6, 'Région'), (7, 'Ronde'), (8, 'Siège'), (9, 'Sommet'), (10, "Structure locale d'activité"), (11, 'Structure locale rattachée'), (12, 'Unité Défi'), (13, 'Unité Eclé'), (14, 'Unité Nomade')], verbose_name='Type'),
        ),
    ]
