# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20160226_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='subtype',
            field=models.IntegerField(blank=True, choices=[(1, 'Centre et terrain'), (2, 'Groupe local'), (3, 'Ludotheque'), (4, 'Service vacances')], null=True, verbose_name='Sous-type'),
        ),
        migrations.AlterField(
            model_name='function',
            name='category',
            field=models.IntegerField(blank=True, choices=[(1, 'Participants'), (2, 'Cadres bénévoles / CEE'), (3, 'Salariés / SC'), (4, 'Amis')], null=True, verbose_name='Categorie'),
        ),
    ]
